### ISSUE TITLE
Association :user not loaded

### ISSUE THREAD

**Issue by raywan** [raywan/qckpoll#4]
```
(Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for #Ecto.Association.NotLoaded<association :user is not loaded>
        (phoenix_html) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
        (phoenix_html) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
        (qckpoll) web/templates/poll/index.html.eex:16: anonymous fn/3 in Qckpoll.PollView.index.html/1
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (qckpoll) web/templates/poll/index.html.eex:13: Qckpoll.PollView."index.html"/1
        (phoenix) lib/phoenix/view.ex:197: Phoenix.View.render_within/3
        (phoenix) lib/phoenix/view.ex:429: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:533: Phoenix.Controller.do_render/4
```

After creating a poll using the built-in form, an error occurs when trying to view poll items.

**Comment by lsandeep83** [comment]
Have you created the associations? In your case, I believe the relationship must be a `user has_many posts` & a `post belongs_to user`

You need to create associations as follows:

**poll_controller.ex**
```
def index(conn, _params) do
    polls = Poll |> Repo.all |> Repo.preload [:user]
    render(conn, "index.html", polls: polls)
end

def show(conn, %{"id" => id}) do
    poll = Poll |> Repo.get(id) |> Repo.preload [:user]
    render(conn, "show.html", poll: poll)
end
```

**user_controller.ex**
```
def index(conn, _params) do
    user = User |> Repo.all |> Repo.preload [:polls]
    render(conn, "index.html", user: user)
end

def show(conn, %{"id" => id}) do
    user = User |> Repo.get(id) |> Repo.preload [:polls]
    render(conn, "show.html", user: user)
end
```

**Comment by raywan** [comment]
```
Request: POST /polls
** (exit) an exception was raised:
    ** (ArgumentError) unknown field `user` (note only fields are supported in cast, associations are not)
        (ecto) lib/ecto/changeset.ex:248: Ecto.Changeset.type!/2
        (ecto) lib/ecto/changeset.ex:231: Ecto.Changeset.process_param/6
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:216: Ecto.Changeset.cast/4
        (qckpoll) web/controllers/poll_controller.ex:20: Qckpoll.PollController.create/2
        (qckpoll) web/controllers/poll_controller.ex:1: Qckpoll.PollController.phoenix_controller_pipeline/2
        (qckpoll) lib/phoenix/router.ex:297: Qckpoll.Router.dispatch/2
        (qckpoll) lib/phoenix/router.ex:2: Qckpoll.Router.call/2
```
